# Generated by Django 5.1.3 on 2025-01-21 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0014_alter_proveedor_options_remove_proveedor_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(default='DEFAULT_RUC', max_length=20, unique=True),
        ),
    ]
